name: "Olive Health"
description: "Olive Health Blog"

url: "http://olive.ai"

paginate: 5
paginate_path: "blog/page:num/"
markdown: rdiscount
permalink: pretty
highlighter: pygments
gems:
    - jekyll-redirect-from
